services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: rag-agent-backend-prod
    ports:
      - "8001:8001"
    networks:
      - rag-agent
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - rag-agent
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-prod

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: rag-agent-frontend-prod
    ports:
      - "8080:80"

networks:
  rag-agent:
    driver: bridge

    