services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rag-agent-backend
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /workspace/backend
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/uv.lock
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rag-agent-frontend
    ports:
      - "5173:5173"
      - "4173:4173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./frontend/package.json
