services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rag-agent-backend
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
      - /workspace/backend/.venv
    ports:
      - "8000:8000"
    networks:
      - rag-agent
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /workspace/backend
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/uv.lock

  
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rag-agent-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # 防止 node_modules 被覆蓋
    ports:
      - "5173:5173"
      - "4173:4173"
    networks:
      - rag-agent
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json

networks:
  rag-agent:
    driver: bridge