FROM --platform=linux/amd64 python:3.10-slim-bookworm AS build_amd64
FROM --platform=linux/arm64 python:3.10-slim-bookworm AS build_arm64


FROM build_${TARGETARCH} AS build
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /build

COPY . .

RUN rm -rf .venv
RUN uv sync --frozen
RUN uv add gunicorn

EXPOSE 8001

CMD ["uv", "run", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8001", "--workers", "4"]
