FROM --platform=linux/amd64 python:3.10-slim-bookworm AS build_amd64
FROM --platform=linux/arm64 python:3.10-slim-bookworm AS build_arm64


FROM build_${TARGETARCH} AS build
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /workspace/backend

COPY . .

RUN rm -rf .venv
RUN uv sync --frozen
RUN uv add gunicorn

# use nginx to host backend service
FROM nginx:alpine AS prod
COPY --from=build /uv /uvx /bin /backend/.venv/
COPY --from=build /nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /workspace/backend/app /workspace/backend/app

EXPOSE 80

CMD ["uv", "run", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8001", "--workers", "4"]